# Generated by Django 3.2.4 on 2021-07-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_auto_20210702_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='author_books', to='book_app.Author'),
        ),
    ]
