# Generated by Django 3.2.4 on 2021-07-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_auto_20210702_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'ordering': ('name',)},
        ),
    ]
