# Generated by Django 3.2.4 on 2021-07-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='dfe 7785 er77', max_length=200),
            preserve_default=False,
        ),
    ]
