# Generated by Django 3.2.4 on 2021-07-03 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_auto_20210703_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 10, 15, 33, 14, 746366)),
        ),
    ]
